In [ ]:
import sqlite3

# SQLiteデータベースを作成
conn = sqlite3.connect("skenes.db")

In [ ]:
import pandas as pd

# CSVファイルを読み込む
reference_2024 = pd.read_csv("2024_paul skines_data_reference.csv")
reference_2025 = pd.read_csv("2025_paul skines_data_reference.csv")

savant_2024 = pd.read_csv("savant_2024_paul skenes.csv")
savant_2025 = pd.read_csv("savant_2025_paul skenes.csv")

savant_pitch_type_2024 = pd.read_csv(
    "savant_2024_paul skenes(pitch type).csv"
)

savant_pitch_type_2025 = pd.read_csv(
    "savant_2025_paul skenes(pitch type).csv"
)

In [ ]:
# 2024年Referenceデータをテーブルに登録
reference_2024.to_sql(
    "reference_2024",
    conn,
    if_exists="replace",
    index=False
)

# 2025年Referenceデータをテーブルに登録
reference_2025.to_sql(
    "reference_2025",
    conn,
    if_exists="replace",
    index=False
)

# 2024年Savantデータをテーブルに登録
savant_2024.to_sql(
    "savant_2024",
    conn,
    if_exists="replace",
    index=False
)

# 2025年Savantデータをテーブルに登録
savant_2025.to_sql(
    "savant_2025",
    conn,
    if_exists="replace",
    index=False
)

# 2024年球種別Savantデータをテーブルに登録
savant_pitch_type_2024.to_sql(
    "savant_pitch_type_2024",
    conn,
    if_exists="replace",
    index=False
)

# 2025年球種別Savantデータをテーブルに登録
savant_pitch_type_2025.to_sql(
    "savant_pitch_type_2025",
    conn,
    if_exists="replace",
    index=False
)

7

In [ ]:
# 2025年の主要成績を取得
query = """
SELECT
    GS AS 先発登板数,
    W AS 勝利,
    L AS 敗戦,
    IP AS 投球回,
    ERA AS 防御率,
    SO AS 奪三振,
    WHIP,
    WAR
FROM reference_2025;
"""

# SQLを実行してデータを取得
main_stats_2025 = pd.read_sql_query(query, conn)

main_stats_2025

   先発登板数  勝利  敗戦    投球回   防御率  奪三振   WHIP  WAR
0     32  10  10  187.2  1.97  216  0.948    8

In [ ]:
from IPython.display import display, HTML

# 2025年の主要成績を表示用に整形
main_stats_2025_display = pd.DataFrame({
    "指標": [
        "先発登板数 (GS)",
        "勝利 (W)",
        "敗戦 (L)",
        "投球回 (IP)",
        "防御率 (ERA)",
        "奪三振 (SO)",
        "WHIP",
        "WAR"
    ],
    "数値": [
        int(main_stats_2025.iloc[0]["先発登板数"]),
        int(main_stats_2025.iloc[0]["勝利"]),
        int(main_stats_2025.iloc[0]["敗戦"]),
        f"{float(main_stats_2025.iloc[0]['投球回']):.1f}",
        f"{float(main_stats_2025.iloc[0]['防御率']):.2f}",
        int(main_stats_2025.iloc[0]["奪三振"]),
        f"{float(main_stats_2025.iloc[0]['WHIP']):.2f}",
        f"{float(main_stats_2025.iloc[0]['WAR']):.1f}"
    ]
})

# HTMLを直接作成
html = """
<table style="
    border-collapse: collapse;
    width: 70%;
    margin: auto;
    table-layout: fixed;
">
    <thead>
        <tr>
            <th style="
                width: 40%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">指標</th>

            <th style="
                width: 60%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">数値</th>
        </tr>
    </thead>

    <tbody>
"""

for _, row in main_stats_2025_display.iterrows():
    html += f"""
    <tr>
        <td style="
            width: 40%;
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['指標']}</td>

        <td style="
            width: 60%;
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['数値']}</td>
    </tr>
    """

html += """
    </tbody>
</table>
"""

display(HTML(html))

In [ ]:
# 2025年の投球内容を取得
query = """
SELECT
    k_percent AS K率,
    bb_percent AS BB率,
    swing_miss_percent AS Whiff率,
    hardhit_percent AS HardHit率,
    xwoba AS xwOBA
FROM savant_2025;
"""

# SQLを実行してデータを取得
pitching_stats_2025 = pd.read_sql_query(query, conn)

pitching_stats_2025

     K率  BB率  Whiff率   HardHit率  xwOBA
0  29.5  5.7    30.1  40.343348  0.255

In [ ]:
from IPython.display import display, HTML

# 2025年の投球内容を表示用に整形
pitching_stats_2025_display = pd.DataFrame({
    "指標": [
        "奪三振率 (K%)",
        "与四球率 (BB%)",
        "空振り率 (Whiff%)",
        "ハードヒット率<br>(Hard-Hit%)",
        "xwOBA"
    ],
    "数値": [
        f"{float(pitching_stats_2025.iloc[0]['K率']):.1f}%",
        f"{float(pitching_stats_2025.iloc[0]['BB率']):.1f}%",
        f"{float(pitching_stats_2025.iloc[0]['Whiff率']):.1f}%",
        f"{float(pitching_stats_2025.iloc[0]['HardHit率']):.1f}%",
        f"{float(pitching_stats_2025.iloc[0]['xwOBA']):.3f}"
    ]
})

# HTMLを直接作成
html = """
<table style="
    border-collapse: collapse;
    width: 70%;
    margin: auto;
    table-layout: fixed;
">
    <thead>
        <tr>
            <th style="
                width: 40%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">指標</th>

            <th style="
                width: 60%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">数値</th>
        </tr>
    </thead>

    <tbody>
"""

for _, row in pitching_stats_2025_display.iterrows():
    html += f"""
    <tr>
        <td style="
            width: 40%;
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['指標']}</td>

        <td style="
            width: 60%;
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['数値']}</td>
    </tr>
    """

html += """
    </tbody>
</table>
"""

display(HTML(html))

In [ ]:
# 2025年の球種別データを取得
query = """
SELECT
    pitch_type AS 球種,
    pitch_percent AS 使用率,
    swing_miss_percent AS Whiff率,
    hardhit_percent AS HardHit率,
    xwoba AS xwOBA
FROM savant_pitch_type_2025;
"""

# SQLを実行してデータを取得
pitch_type_stats_2025 = pd.read_sql_query(query, conn)

pitch_type_stats_2025

   球種   使用率  Whiff率   HardHit率  xwOBA
0  FF  38.9    29.6  53.293413  0.280
1  ST  15.8    32.9  19.178082  0.209
2  FS  13.5    22.8  44.871795  0.308
3  CH  10.9    43.9  11.627907  0.123
4  SI  10.4    16.7  49.275362  0.284
5  SL   5.6    33.8  16.666667  0.204
6  CU   4.8    40.8  44.444444  0.368

In [ ]:
from IPython.display import display, HTML

# 球種名を日本語に変換
pitch_name = {
    "FF": "フォーシーム",
    "ST": "スイーパー",
    "FS": "スプリット",
    "CH": "チェンジアップ",
    "SI": "シンカー",
    "SL": "スライダー",
    "CU": "カーブ"
}

# 2025年の球種別データを表示用に整形
pitch_type_stats_2025_display = pd.DataFrame({
    "球種": [
        pitch_name.get(pitch, pitch)
        for pitch in pitch_type_stats_2025["球種"]
    ],
    "使用率": [
        f"{float(value):.1f}%"
        for value in pitch_type_stats_2025["使用率"]
    ],
    "空振り率 (Whiff%)": [
        f"{float(value):.1f}%"
        for value in pitch_type_stats_2025["Whiff率"]
    ],
    "xwOBA": [
        f"{float(value):.3f}"
        for value in pitch_type_stats_2025["xwOBA"]
    ]
})

# HTMLを直接作成
html = """
<table style="
    border-collapse: collapse;
    width: 75%;
    margin: auto;
    table-layout: fixed;
">
    <thead>
        <tr>
            <th style="
                width: 25%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">球種</th>

            <th style="
                width: 25%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">使用率</th>

            <th style="
                width: 25%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">空振り率 (Whiff%)</th>

            <th style="
                width: 25%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">xwOBA</th>
        </tr>
    </thead>

    <tbody>
"""

# 各行を追加
for _, row in pitch_type_stats_2025_display.iterrows():
    html += f"""
    <tr>
        <td style="
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['球種']}</td>

        <td style="
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['使用率']}</td>

        <td style="
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['空振り率 (Whiff%)']}</td>

        <td style="
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['xwOBA']}</td>
    </tr>
    """

html += """
    </tbody>
</table>
"""

# 表を表示
display(HTML(html))

In [ ]:
# 2024年・2025年の主要成績を比較
query = """
SELECT
    '2024' AS 年,
    IP AS 投球回,
    ERA AS 防御率,
    SO AS 奪三振,
    WHIP,
    WAR
FROM reference_2024

UNION ALL

SELECT
    '2025' AS 年,
    IP AS 投球回,
    ERA AS 防御率,
    SO AS 奪三振,
    WHIP,
    WAR
FROM reference_2025;
"""

comparison_stats = pd.read_sql_query(query, conn)

comparison_stats

      年    投球回   防御率  奪三振   WHIP  WAR
0  2024  133.0  1.96  170  0.947  5.8
1  2025  187.2  1.97  216  0.948  8.0

In [ ]:
# 2024年・2025年のK%・BB%を取得
query = """
SELECT
    '2024' AS 年,
    k_percent AS K率,
    bb_percent AS BB率
FROM savant_2024

UNION ALL

SELECT
    '2025' AS 年,
    k_percent AS K率,
    bb_percent AS BB率
FROM savant_2025;
"""

rate_stats = pd.read_sql_query(query, conn)

rate_stats

      年    K率  BB率
0  2024  33.1  6.2
1  2025  29.5  5.7

In [ ]:
# 主要成績とK%・BB%を結合
comparison_stats = comparison_stats.merge(
    rate_stats,
    on="年"
)

comparison_stats

      年    投球回   防御率  奪三振   WHIP  WAR    K率  BB率
0  2024  133.0  1.96  170  0.947  5.8  33.1  6.2
1  2025  187.2  1.97  216  0.948  8.0  29.5  5.7

In [ ]:
from IPython.display import display, HTML

# 2024年・2025年比較表を表示用に整形
comparison_display = pd.DataFrame({
    "指標": [
        "投球回 (IP)",
        "防御率 (ERA)",
        "奪三振 (SO)",
        "奪三振率 (K%)",
        "与四球率 (BB%)",
        "WHIP",
        "WAR"
    ],
    "2024": [
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2024', '投球回'].iloc[0]):.1f}",
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2024', '防御率'].iloc[0]):.2f}",
        int(comparison_stats.loc[comparison_stats['年'] == '2024', '奪三振'].iloc[0]),
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2024', 'K率'].iloc[0]):.1f}%",
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2024', 'BB率'].iloc[0]):.1f}%",
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2024', 'WHIP'].iloc[0]):.2f}",
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2024', 'WAR'].iloc[0]):.1f}"
    ],
    "2025": [
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2025', '投球回'].iloc[0]):.1f}",
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2025', '防御率'].iloc[0]):.2f}",
        int(comparison_stats.loc[comparison_stats['年'] == '2025', '奪三振'].iloc[0]),
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2025', 'K率'].iloc[0]):.1f}%",
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2025', 'BB率'].iloc[0]):.1f}%",
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2025', 'WHIP'].iloc[0]):.2f}",
        f"{float(comparison_stats.loc[comparison_stats['年'] == '2025', 'WAR'].iloc[0]):.1f}"
    ]
})

# HTMLを直接作成
html = """
<table style="
    border-collapse: collapse;
    width: 75%;
    margin: auto;
    table-layout: fixed;
">
    <thead>
        <tr>
            <th style="
                width: 24%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">指標</th>

            <th style="
                width: 38%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">2024</th>

            <th style="
                width: 38%;
                border: 1px solid black;
                text-align: center;
                padding: 8px;
                background-color: #F2F2F2;
            ">2025</th>
        </tr>
    </thead>

    <tbody>
"""

for _, row in comparison_display.iterrows():
    html += f"""
    <tr>
        <td style="
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['指標']}</td>

        <td style="
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['2024']}</td>

        <td style="
            border: 1px solid black;
            text-align: center;
            vertical-align: middle;
            padding: 8px;
        ">{row['2025']}</td>
    </tr>
    """

html += """
    </tbody>
</table>
"""

display(HTML(html))